### ISSUE TITLE
Issue with classdumpios on latest macOS Version

### ISSUE THREAD

**Issue by Mx-Iris** [lechium/UIFocusHelper#1]
Hello @lechium,

I hope you are doing well. First and foremost, I would like to apologize for reaching out to you in this manner. I've encountered an issue with a project that you have forked (class-dump), and I noticed that the 

issue tracker was not available there, so I opted to contact you through an active repository of yours.

I have been using the `classdumpios` utility to extract header information from macOS Framework binaries, which were extracted using the `dyld-shared-cache-extractor`. Unfortunately, I encountered an assertion failure when attempting to execute `class-dump` on these binaries on the latest version of macOS.

Any guidance you could offer on this matter would be greatly appreciated. If there's a better channel for me to report this issue, please let me know.

Thank you for your understanding and for your contributions to the open-source community. I look forward to hearing from you.

<img width="1859" alt="iShot_2024-01-20_21 07 33" src="https://github.com/lechium/UIFocusHelper/assets/61279231/c139bf13-12d3-4572-99c3-b55c7be7c7a7">

**Comment by lechium** [comment]
has it worked on prior versions with bins extracted from dyld cache? because i could never get it to work like that before. bins extracted from dyld arent typically extracted "properly" to keep the address information in the expected places.

**Comment by Mx-Iris** [comment]
@lechium Thank you for your reply, I may have misrepresented myself, it's also my first time trying to extract header files from the dyld cache, so far I only found this [w0lfschild/macOS_headers](https://github.com/w0lfschild/macOS_headers) the author stated that it was extracted using a modified dsdump, and I've tried a lot of methods and a lot of versions of class- dump are not able to extract header files in the latest macOS.
Do you have any other way to dump the macOS headers?

**Comment by lechium** [comment]
unfortunately at this moment i do not. there is a [classdump-dyld](https://github.com/lechium/classdump-dyld) project from limneos that i maintained a fork of and updated for a while but i havent touched it since apple started using new linking flags that broke most other versions of class dump. presumably that project could be updated to work on newer cache files. unfortunately i dont have the free time, or patience necessary to undertake that task.

**Comment by lechium** [comment]
@Mx-Iris just fyi I never realized issues was missing from [classdumpios](https://github.com/lechium/classdumpios) that wasnt an intentional decision, thought that was there by default. maybe it preserves the settings of the repository i forked from? either way there is now an issue tracker for that repository. im going to close this issue and you can re-open one there if you would like.
